config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :plans, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user

  enum prefecture:{
    "都道府県":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  enum stay_days:{
    "宿泊日数":0,
    日帰り:1,一泊二日:2,二泊三日:3,三泊四日:4,四泊～:5
  }

  enum budget:{
    "予算":0,
    "～1万":1,"1万～2万":2,"2万～3万":3,"3万～4万":4,"4万～5万":5,"5万～":6
  }

  enum main_vehicle:{
    "主な移動手段":0,
    自動車:1,公共交通機関:2,それ以外:3
  }

  has_one_attached :plan_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :plans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    @plan.save
    redirect_to plans_path(@plan)
  end

  def index
    @plans = Plan.all
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :prefecture, :stay_days, :budget, :main_vehicle, :impression, :plan_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<% if user_signed_in? %>
  <li>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  </li>
  <li>
    <%= link_to "Plan", new_plan_path %>
  </li>
<% else %>
  <li>
    <%= link_to "new", new_user_registration_path %>
  </li>
  <li>
    <%= link_to "Log in", new_user_session_path %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Y</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/index.html.erb
<h1>プラン一覧</h1>
<div>
  <% @plans.each do |plan| %>
    <%= image_tag plan.plan_image %>
    <%= plan.title %>
    <%= plan.prefecture %>
    <%= plan.stay_days %>
    <%= plan.budget %>
    <%= plan.main_vehicle %>
    <%= plan.impression %>
  <% end %>
</div>

app/views/plans/new.html.erb
<h2>プラン入力</h2>
<%= form_with model: @plan, method: :post do |f| %>
  <div class="form_group">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>
  <div class="form_group">
    <%= f.label :都道府県 %>
    <%= f.select :prefecture, Plan.prefectures.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :宿泊日数 %>
    <%= f.select :stay_days, Plan.stay_days.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :予算 %>
    <%= f.select :budget, Plan.budgets.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :主な移動手段 %>
    <%= f.select :main_vehicle, Plan.main_vehicles.keys, {} %>
  </div>
  <div class="form_group">
    <%= f.label :感想 %>
    <%= f.text_area :impression %>
  </div>
  <div class="form-group">
    <%= f.label :プラン画像 %>
    <%= f.file_field :plan_image, class: "form-control-file", accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.submit "スケジュール入力", class: "btn btn-info" %>
  </div>
<% end %>